package com.maxjin.a11y.ui.theme

import androidx.compose.ui.graphics.Color

val Magenta = Color(0xFFE20074)
val MagentaDark = Color(0xFFA10053)
val Transparent = Color(0x00FFFFFF)
val Black = Color(0xFF000000)
val White = Color(0xFFFFFFFF)
val bg_gradient_start = Color(0xFFFDD8E9)
val bg_gradient_end = Color(0xFFD7E3F3)

// Light Scheme Colors
val LightPrimary = Color(0xFFba005e)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFffd9e1)
val LightOnPrimaryContainer = Color(0xFF3f001c)
val LightSecondary = Color(0xFFba005e)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFffd9e1)
val LightOnSecondaryContainer = Color(0xFF3f001c)
val LightTertiary = Color(0xFF00639c)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFcee5ff)
val LightOnTertiaryContainer = Color(0xFF001d33)
//val LightTertiary = Color(0xFFad295f)
//val LightOnTertiary = Color(0xFFffffff)
//val LightTertiaryContainer = Color(0xFFffd9e1)
//val LightOnTertiaryContainer = Color(0xFF3f001c)

// Dark Scheme Colors
val DarkPrimary = Color(0xFFffb1c6)
val DarkOnPrimary = Color(0xFF650030)
val DarkPrimaryContainer = Color(0xFF8e0047)
val DarkOnPrimaryContainer = Color(0xFFffd9e1)
val DarkSecondary = Color(0xFFffb1c6)
val DarkOnSecondary = Color(0xFF650030)
val DarkSecondaryContainer = Color(0xFF8e0047)
val DarkOnSecondaryContainer = Color(0xFFffd9e1)
val DarkTertiary = Color(0xFF98cbff)
val DarkOnTertiary = Color(0xFF003354)
val DarkTertiaryContainer = Color(0xFF004a77)
val DarkOnTertiaryContainer = Color(0xFFcee5ff)
//val DarkTertiary = Color(0xFFffb1c6)
//val DarkOnTertiary = Color(0xFF650030)
//val DarkTertiaryContainer = Color(0xFF8e0047)
//val DarkOnTertiaryContainer = Color(0xFFffd9e1)