/*
 * 2023 - Developed by Max Jin
 * Source code subject to change. Refer to NOTICE.txt in source tree for changes and attributions.
 */

package com.maxjin.a11y.ui.nav

enum class NavDestination(val id: String) {
    APP_HOME("APP_HOME"),
    APP_SEARCH("APP_SEARCH"),
    COMPONENT_BUTTON("COMPONENT_BUTTON"),
    COMPONENT_CHECKBOX("COMPONENT_CHECKBOX"),
    COMPONENT_LINK("COMPONENT_LINK"),
    COMPONENT_RADIO_BUTTON("COMPONENT_RADIO_BUTTON"),
    COMPONENT_TEXT_FIELD("COMPONENT_TEXT_FIELD"),
    COMPONENT_SWITCH("COMPONENT_SWITCH"),
    COMPONENT_ALERT_DIALOG("COMPONENT_ALERT_DIALOG"),
    COMPONENT_SNACKBAR("COMPONENT_SNACKBAR"),
    COMPONENT_CAROUSEL("COMPONENT_CAROUSEL")
}